project:
  type: website
  resources: netlify.toml

website:
  title: "Home"
  site-url: "https://www.pietstam.nl"

  favicon: favicon.png

  navbar:
    right:
      - text: Blog
        href: posts.qmd
      - text: Publications
        href: publications.qmd
      - icon: twitter
        href: https://twitter.com/pjastam
      - icon: linkedin
        href: https://www.linkedin.com/in/pjastam
      - icon: github
        href: https://github.com/pjastam


  page-footer:
    left: |
      Copyright (c) 2022 [Piet Stam](https://www.pietstam.nl). Except where otherwise noted, content on this site is licensed under a <br>
      {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license](https://creativecommons.org/licenses/by-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
      View the source at [{{< fa brands github >}} GitHub](https://github.com/pjastam/blog-quarto)

format:
  html:
    theme: 
      light: sketchy
      dark: slate
