project:
  type: website

website:
  title: "Home"
  site-url: "https://www.pietstam.nl"
  navbar:
    right:
      - posts.qmd
      - icon: github
        href: https://github.com/pjastam
      - icon: twitter
        href: https://twitter.com/pjastam
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

