project:
  type: website

website:
  title: "blog"
  site-url: "https://www.pietstam.nl"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

