project:
  type: website
  resources:
    - netlify.toml

website:
  title: "Home"
  site-url: "https://www.pietstam.nl"
  navbar:
    right:
      - text: Blog
        href: posts.qmd
      - text: Publications
        href: publications.qmd
      - icon: github
        href: https://github.com/pjastam
      - icon: twitter
        href: https://twitter.com/pjastam
format:
  html:
    theme: superhero
    css: styles.css

editor: visual
