# Map URIs to pjastam.github.io repo
# The reason is that the domain name pietstam.nl was removed from this blogdown-jekyll repo at GitHub

[[redirects]]
  from = "/coronavirus_dashboard"
  to = "https://pjastam.github.io/coronavirus-dashboard"
  status = 301
  force = true

[[redirects]]
  from = "/coronavirus-dashboard"
  to = "https://pjastam.github.io/coronavirus-dashboard"
  status = 301
  force = true
  
[[redirects]]
  from = "/phdthesis"
  to = "https://pjastam.github.io/phdthesis"
  status = 301
  force = true

[[redirects]]
  from = "/mscthesis"
  to = "https://pjastam.github.io/mscthesis"
  status = 301
  force = true

[[redirects]]
  from = "/msc-thesis-arfima"
  to = "https://pjastam.github.io/msc-thesis-arfima"
  status = 301
  force = true

# Migration from blog-jekyll to blog-quarto

[[redirects]]
  from = "/about"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/posts"
  status = 301
  force = true

[[redirects]]
  from = "/credits"
  to = "/"
  status = 301
  force = true

# In the redirects below I use splat and wildcard rules to redirect all blog pages in one go
# Source of this idea: https://cryolayer.com/tutorials/editing-redirect-rules-on-your-webflow-site

# Map blog posts URIs from blog-jekyll to blog-quarto

[[redirects]]
  from = "/blog/:year/:month/:day/*"
  to = "/posts/:year-:month-:day-:splat"
  status = 301
  force = true

# Map blog posts URIs from blog-hugo to blog-quarto

[[redirects]]
  from = "/post/*"
  to = "/posts/:splat"
